/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moduloProductos;


import ejercicio.tiendaciclismo.Archivos;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import moduloFacturacion.Factura;
import moduloFacturacion.RegistroFacturacion;

/**
 * La clase EditarArticulo es una interfaz gráfica de usuario (GUI) que permite
 * agregar, modificar o eliminar artículos en un sistema de gestión de productos.
 * Los artículos se muestran en una tabla y se pueden editar mediante la
 * interacción del usuario con los componentes de la interfaz.
 * @author Jimena Mendez
 */
public class EditarArticulo extends javax.swing.JFrame {
    DefaultTableModel tablaArticulo=new DefaultTableModel();
    private Archivos reg = new Archivos();
    private RegistroProductos registro = new RegistroProductos();
    
    /**
     * Constructor de la clase EditarArticulo. Inicializa la interfaz gráfica y
     * carga los datos necesarios para la operación del sistema.
     */
    public EditarArticulo() {
        registro.ProductosArchivo(reg.leer("tiposProductos.csv"));
        registro.ArticulosArchivo(reg.leer("Articulos.csv"));
        
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Configuración de la tabla
        String articulos[]={"Código","Producto","Nombre","Tipo","Tamaño","Marca","Precio","Cantidad"};
        
        tablaArticulo.setColumnIdentifiers(articulos);
        
        jTable1.setModel(tablaArticulo);
        
        jTable1.setDefaultEditor(Object.class, null);
        
        
        // Inicialización de la tabla con los datos existentes
        iniciarTabla();
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(157, 232, 201));
        jPanel1.setPreferredSize(new java.awt.Dimension(1031, 556));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Editar artículos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 19, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Rellene los siguientes espacios si desea agregar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("o modificar un artículo.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 87, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Producto:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Tipo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Tamaño:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 309, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("Marca:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("Precio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, -1, -1));

        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Nombre", "Tipo", "Tamaño", "Marca", "Precio", "Cantidad"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 844, 453));

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 296, -1));

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicicleta", "Accesorios", "Suplementos alimenticios" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextField3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 296, -1));

        jTextField4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 296, -1));

        jTextField5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 296, -1));

        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "22", "26", "27", "27.5", "29" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 339, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Método que maneja el evento de clic en el botón "Modificar". Obtiene los
     * datos ingresados por el usuario y realiza la modificación del artículo
     * seleccionado en la tabla y en la fuente de datos.
     *
     * @param evt Evento de acción generado por el botón "Modificar".
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if (!jTextField1.getText().isEmpty() && !jTextField3.getText().isEmpty() && !jTextField4.getText().isEmpty() && !jTextField5.getText().isEmpty()){ 
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                int fila=jTable1.getSelectedRow();
                if (fila >= 0) {
                registro.modificarArticulo(registro.getArticulos().get(fila).getCodigo(), registro.getArticulos().get(fila).getCodigoTipoProducto(), jTextField1.getText(), jComboBox2.getSelectedItem().toString(), Integer.parseInt(jComboBox3.getSelectedItem().toString()), jTextField3.getText(), (int) Double.parseDouble(jTextField4.getText()), Integer.parseInt(jTextField5.getText()));
                
                model.setValueAt(jTextField1.getText(),fila , 2);
                model.setValueAt(jComboBox2.getSelectedItem().toString(), fila, 3);
                model.setValueAt(Integer.valueOf(jComboBox3.getSelectedItem().toString()), fila, 4);
                model.setValueAt(jTextField3.getText(), fila, 5);
                model.setValueAt(Double.valueOf(jTextField4.getText()), fila, 6);
                model.setValueAt(Integer.valueOf(jTextField5.getText()), fila, 7);
                JOptionPane.showMessageDialog(null, "Se ha modificado el articulo", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                jButton2.setEnabled(false);
                jButton3.setEnabled(false);
                }
            }else{
                JOptionPane.showMessageDialog(jPanel1, "Debe rellenar los espacios.");
                return;
            }
            
            limpiarCampos();
            iniciarTabla();
            
        }catch (Exception e){
            limpiarCampos();
            JOptionPane.showMessageDialog(jPanel1, "Debe seleccionar una fila.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * Método que maneja el evento de clic en el botón "Eliminar". Verifica si
     * se puede eliminar el artículo seleccionado y realiza la eliminación si es
     * posible.
     *
     * @param evt Evento de acción generado por el botón "Eliminar".
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (confirmacion()){
            try{
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                int filaSeleccionada=jTable1.getSelectedRow();
                
                if (!articuloFacturado(registro.getArticulos().get(filaSeleccionada).getCodigo(),registro.getArticulos().get(filaSeleccionada).getCodigoTipoProducto() )){
                    registro.deleteArticulo(registro.getArticulos().get(filaSeleccionada).getCodigo(),registro.getArticulos().get(filaSeleccionada).getCodigoTipoProducto() );
                    limpiarCampos();
                    model.removeRow(filaSeleccionada);
                    iniciarTabla();
                    JOptionPane.showMessageDialog(null, "Se ha eliminado el articulo", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    jComboBox1.setEnabled(true);
                    jButton2.setEnabled(false);
                    jButton3.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(jPanel1, "El artículo no puede ser eliminado porque se encuentra facturado");
                }
            }catch (Exception e){
                jComboBox1.setEnabled(true);
                JOptionPane.showMessageDialog(jPanel1, "Debe seleccionar una fila.");
            }
        }else{
            JOptionPane.showMessageDialog(jPanel1, "No se elimino el producto.");
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * Método que muestra un cuadro de diálogo de confirmación y devuelve true
     * si el usuario elige realizar la acción, o false si cancela.
     *
     * @return true si el usuario confirma, false si cancela.
     */
    private boolean confirmacion(){
        int opcion = JOptionPane.showConfirmDialog(jPanel1,
                    "¿Desea realizar la acción?",
                    "Confirmación",
                    JOptionPane.OK_CANCEL_OPTION);

            if (opcion == JOptionPane.OK_OPTION) {
                return true;
            } else {
                return false;
            }
    }
    
    
    /**
     * Método que verifica si un artículo está asociado a alguna factura en el
     * sistema.
     *
     * @param codigo Código del artículo.
     * @param codigoProducto Código del producto al que pertenece el artículo.
     * @return true si el artículo está facturado, false si no lo está.
     */
    private boolean articuloFacturado(int codigo,int codigoProducto){
        RegistroFacturacion registroFacturas=new RegistroFacturacion();
        registroFacturas.FacturasArchivo(reg.leer("Facturas"));
        
        for(Factura factura:registroFacturas.getFacturas()){
            int codigoExiste= factura.getCodigoArticulo();
            int codigoProductoExiste=factura.getCodigoProducto();
            if (codigoExiste==codigo && codigoProductoExiste==codigoProducto){
                return true;
            }
        }
        return false;
    }
    
    /**
     * Método que maneja el evento de clic en el botón "Agregar". Agrega un
     * nuevo artículo con los datos proporcionados por el usuario.
     *
     * @param evt Evento de acción generado por el botón "Agregar".
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!jTextField1.getText().trim().isEmpty() && !jTextField3.getText().isEmpty() && !jTextField4.getText().trim().isEmpty() && !jTextField5.getText().isEmpty()){
            for (Articulo art:registro.getArticulos()){
                String nombreGuardado=art.getNombre();
                if (nombreGuardado.equalsIgnoreCase(jTextField1.getText())){
                    limpiarCampos();
                    JOptionPane.showMessageDialog(jPanel1, "Debe agregar un articulo que no tenga ese nombre.");
                    return;
                }
            }
            
            
            
            // Ahora se busca el codigo con el nombre del producto elegido
            int codigoProducto=registro.codigoProducto(jComboBox1.getSelectedItem().toString());
            
            
            //Se cambian los demas atributos
            int tamano= Integer.parseInt(jComboBox3.getSelectedItem().toString());
            int precio=Integer.parseInt(jTextField4.getText());
            int cantidad=Integer.parseInt(jTextField5.getText());
            
            registro.agregarArticulo(codigoProducto, jTextField1.getText() , jComboBox2.getSelectedItem().toString(), tamano, jTextField3.getText(), precio , cantidad);
            
            iniciarTabla();
            JOptionPane.showMessageDialog(null, "Se ha agregado el articulo", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            limpiarCampos();
            
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Debe rellenar los espacios con el formato correcto.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    /**
     * Método que maneja el evento de clic en el botón "Regresar". Vuelve a la
     * ventana principal del sistema.
     *
     * @param evt Evento de acción generado por el botón "Regresar".
     */

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ProductosVentana v1=new ProductosVentana();
        v1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    
    /**
     * Método que maneja el evento de selección en el combo box "Tipo". Actualiza
     * la lista de tamaños disponibles según el tipo seleccionado.
     *
     * @param evt Evento de acción generado por el combo box "Tipo".
     */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String tipo = (String) jComboBox2.getSelectedItem();
        if ("Bicicleta".equals(tipo)){
            String [] tipos = {"12", "16", "22", "26", "27", "27.5","29"};
            jComboBox3.removeAllItems();
            for (int indice=0 ; tipos.length != indice; indice++){
               jComboBox3.addItem(tipos[indice]);
            }
        }else{
            jComboBox3.removeAllItems();
            jComboBox3.addItem("0");
            jComboBox3.setEditable(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * Método que maneja el evento de selección en el combo box "Tamaño".
     *
     * @param evt Evento de acción generado por el combo box "Tamaño".
     */
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char numero = evt.getKeyChar();
        if (!(Character.isDigit(numero)) || (numero == KeyEvent.VK_BACK_SPACE) || (numero == KeyEvent.VK_DELETE)){
            evt.consume();
        } 
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        char numero = evt.getKeyChar();
        if (!(Character.isDigit(numero)) || (numero == KeyEvent.VK_BACK_SPACE) || (numero == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char letra = evt.getKeyChar();
        if (!(Character.isLetter(letra) || letra == ' ' || letra == KeyEvent.VK_BACK_SPACE || letra == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char letra = evt.getKeyChar();
        if (!(Character.isLetter(letra) || letra == ' ' || letra == KeyEvent.VK_BACK_SPACE || letra == KeyEvent.VK_DELETE)){
            evt.consume();
        }    
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Método que maneja el evento de clic en una celda de la tabla. Llena los
     * campos de edición con los datos del artículo seleccionado.
     *
     * @param evt Evento de acción generado por el clic en una celda de la tabla.
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        try{
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int filaSeleccionada=jTable1.getSelectedRow();     
            jTextField1.setText((String) model.getValueAt(filaSeleccionada, 2));
      
            //Se busca el nombre del producto que se le dio al articulo
            String nombreProducto=registro.getTiposProductos().get(filaSeleccionada).getNombre();
       
            jComboBox1.setSelectedItem(nombreProducto);
            jComboBox2.setSelectedItem(model.getValueAt(filaSeleccionada, 3).toString());
            jComboBox3.setSelectedItem(model.getValueAt(filaSeleccionada, 4).toString());
            jTextField3.setText(model.getValueAt(filaSeleccionada, 5).toString());
            jTextField4.setText(model.getValueAt(filaSeleccionada, 6).toString());
            jTextField5.setText(model.getValueAt(filaSeleccionada, 7).toString());
    
        }catch (Exception e){
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    
    /**
     * Método que inicia la tabla con los datos de los artículos existentes en
     * el sistema.
     */
    private void iniciarTabla(){
        tablaArticulo.setRowCount(0);
        for (Articulo art:registro.getArticulos()){
            Object[] filaArt={art.getCodigo(),art.getCodigoTipoProducto(),art.getNombre(),art.getTipo(),art.getTamano(),art.getMarca(),art.getPrecio(),art.getCantidad()};
            tablaArticulo.addRow(filaArt);
        }
        
        jComboBox1.removeAllItems();
        for(TipoProducto producto:registro.getTiposProductos()){
            String nombre= producto.getNombre();
            jComboBox1.addItem(nombre);
                    
        }
        
        
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    
    /**
     * Método que inicia la tabla con los datos de los artículos existentes en
     * el sistema.
     */ 
    public void limpiarCampos(){
        jComboBox1.setEnabled(true);
        jTextField1.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditarArticulo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
